name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Set your desired Python version

#      - name: Install dependencies
#        run: |
#          pip install -r requirements.txt  # If you have any dependencies

      - name: Extract developer data
        run: python docs/extract_developers.py  # Make sure the script is named correctly

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./docs  # Adjust if needed
